# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'WegfinderChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WegfinderChallenge
  pod 'Nuke', '~> 8.4'

  target 'WegfinderChallengeTests' do
    inherit! :search_paths
    
  end

end
